### ISSUE TITLE
About Model

### ISSUE THREAD

**Issue by FRunyang** [HowieMa/NSRMhand#1]
Hello,can you offer your models?

**Comment by FRunyang** [comment]
I want to test it.

**Comment by FRunyang** [comment]
@HowieMa

**Comment by HowieMa** [comment]
Hi, sorry for the late response. Due to the email notification setting of my Github, I just found your issues. I have already release our trained model (LPM G1&6), you can download it from [here](https://www.dropbox.com/s/b83ongnpggeoebd/best_model.pth?dl=0). Besides, I also add an inference code to help you test it. If you have any questions, please do not hesitate to contact. Thank you!
