### ISSUE TITLE
./CPM used in training? 

### ISSUE THREAD

**Issue by HollyDQWang** [HowieMa/NSRMhand#16]
Is the model in ./CPM folder used anywhere in the training process of the limb model? I think there are quite a few duplicated code in ./CPM as well as in other parts of the code body such as in main.py and in hand_ldm.py, etc. and I got confused in which files actually were used in training.

**Comment by HowieMa** [comment]
The "CPM" folder is only used for the baseline training of the CPM model. It only uses the data loader function in "CPM/cmuhand.py", and only uses the CPM baseline model in "CPM/cpm.py". Thus, in general, this is just the baseline model. 

I treat it separately simply because there are lots of differences in the detailed implementation. Thus there may be a few duplicated codes in it. 

The data loader functions for our proposed "LPM" or "LDM" is in "dataset/hand_lpm.py" and "dataset/hand_ldm.py", respectively.
